AWSTemplateFormatVersion: 2010-09-09

Description: |
  EC2 instance for static web page
  
#Parameters:
  
Resources:

  ec2SgMain:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh and http from anywhere
      GroupName: altaz-carousel-sg
      SecurityGroupIngress: 
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0


  
#Outputs:
